import React, { useState, useMemo } from 'react';
import { 
  DollarSign, 
  Layers, 
  Calculator, 
  TrendingUp, 
  Sparkles, 
  AlertCircle 
} from 'lucide-react';
import { Tenant } from '../../types';

interface BusinessWidgetsProps {
  tenant: Tenant;
}

// ----------------------------------------------------
// 1. Revenue Attribution Tracker
// ----------------------------------------------------
export const RevenueAttribution: React.FC<BusinessWidgetsProps> = ({ tenant }) => {
  // Derive value generated by lead count and appointment count
  const leadsCount = tenant.leads?.length || 0;
  const appointmentsCount = tenant.appointments?.length || 0;

  // Assuming an average lead value of $150 and booking value of $300
  const estimatedRevenue = useMemo(() => {
    return (leadsCount * 150) + (appointmentsCount * 300);
  }, [leadsCount, appointmentsCount]);

  const bookingShare = useMemo(() => {
    if (estimatedRevenue === 0) return 50;
    return Math.round(((appointmentsCount * 300) / estimatedRevenue) * 100);
  }, [appointmentsCount, estimatedRevenue]);

  return (
    <div className="bg-[#080b12] border border-white/5 p-5 rounded-3xl space-y-4 shadow-xl select-none">
      <div className="flex items-center justify-between">
        <p className="text-[10px] font-bold font-mono text-slate-450 uppercase tracking-widest flex items-center gap-1.5">
          <DollarSign className="h-3.5 w-3.5 text-emerald-450" />
          <span>Revenue Attribution</span>
        </p>
        <span className="text-[9.5px] font-mono text-emerald-450 bg-[#10b881]/10 px-2 py-0.5 border border-emerald-500/20 rounded font-semibold whitespace-nowrap">
          Live Yield
        </span>
      </div>

      <div className="space-y-1.5 pt-2">
        <span className="text-2xl font-bold font-mono text-white block select-all">
          ${estimatedRevenue.toLocaleString()}
        </span>
        <p className="text-[9.5px] font-mono text-slate-500 leading-normal">
          Estimated financial yield attributed directly to AI chat leads and automated bookings.
        </p>
      </div>

      <div className="space-y-2 border-t border-white/5 pt-3">
        <div className="flex items-center justify-between text-xs font-mono">
          <span className="text-slate-400">Booking Revenue:</span>
          <span className="font-bold text-white">${(appointmentsCount * 300).toLocaleString()} ({bookingShare}%)</span>
        </div>
        <div className="flex items-center justify-between text-xs font-mono">
          <span className="text-slate-400">CRM Leads Revenue:</span>
          <span className="font-bold text-white">${(leadsCount * 150).toLocaleString()} ({100 - bookingShare}%)</span>
        </div>
      </div>
    </div>
  );
};

// ----------------------------------------------------
// 2. Subscription Usage Meter
// ----------------------------------------------------
export const SubscriptionUsageMeter: React.FC<BusinessWidgetsProps> = ({ tenant }) => {
  // Configured quotas
  const limits = {
    messages: 5000,
    kbDocs: 50,
    agents: 10,
    apiCalls: 1000
  };

  const usage = useMemo(() => {
    // Generate deterministic values based on actual length/name
    const msgSeed = (tenant.leads?.length || 0) * 80 + 1200;
    const kbSeed = tenant.knowledgeBase?.length || 5;
    const agentSeed = tenant.agents?.length || 1;
    const apiSeed = msgSeed + 450;

    return {
      messages: Math.min(limits.messages, msgSeed),
      kbDocs: Math.min(limits.kbDocs, kbSeed),
      agents: Math.min(limits.agents, agentSeed),
      apiCalls: Math.min(limits.apiCalls, apiSeed)
    };
  }, [tenant]);

  return (
    <div className="bg-[#080b12] border border-white/5 p-5 rounded-3xl space-y-4 shadow-xl select-none">
      <div className="flex items-center justify-between">
        <p className="text-[10px] font-bold font-mono text-slate-450 uppercase tracking-widest flex items-center gap-1.5">
          <Layers className="h-3.5 w-3.5 text-blue-450" />
          <span>Plan Usage Meter</span>
        </p>
        <span className="text-[9.5px] font-mono text-slate-400">Premium Plan</span>
      </div>

      <div className="space-y-3 pt-2">
        {/* Messages */}
        <div className="space-y-1 font-mono text-xs">
          <div className="flex items-center justify-between">
            <span className="text-slate-400 text-[10px]">Monthly Inbounds</span>
            <span className="text-white font-bold text-[10.5px]">
              {usage.messages} / {limits.messages}
            </span>
          </div>
          <div className="h-2 bg-white/5 border border-white/5 rounded-full overflow-hidden">
            <div 
              style={{ width: `${(usage.messages / limits.messages) * 100}%` }} 
              className="h-full bg-blue-500 rounded-full"
            />
          </div>
        </div>

        {/* KB Storage */}
        <div className="space-y-1 font-mono text-xs">
          <div className="flex items-center justify-between">
            <span className="text-slate-400 text-[10px]">Knowledge Base Docs</span>
            <span className="text-white font-bold text-[10.5px]">
              {usage.kbDocs} / {limits.kbDocs}
            </span>
          </div>
          <div className="h-2 bg-white/5 border border-white/5 rounded-full overflow-hidden">
            <div 
              style={{ width: `${(usage.kbDocs / limits.kbDocs) * 100}%` }} 
              className="h-full bg-purple-500 rounded-full"
            />
          </div>
        </div>

        {/* API Calls */}
        <div className="space-y-1 font-mono text-xs">
          <div className="flex items-center justify-between">
            <span className="text-slate-400 text-[10px]">RAG Vector API Queries</span>
            <span className={`font-bold text-[10.5px] ${usage.apiCalls > limits.apiCalls * 0.85 ? 'text-amber-400' : 'text-white'}`}>
              {usage.apiCalls} / {limits.apiCalls}
            </span>
          </div>
          <div className="h-2 bg-white/5 border border-white/5 rounded-full overflow-hidden">
            <div 
              style={{ width: `${(usage.apiCalls / limits.apiCalls) * 100}%` }} 
              className={`h-full rounded-full ${usage.apiCalls > limits.apiCalls * 0.85 ? 'bg-amber-500' : 'bg-emerald-500'}`}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

// ----------------------------------------------------
// 3. ROI Calculator (Interactive!)
// ----------------------------------------------------
export const ROICalculator: React.FC<BusinessWidgetsProps> = ({ tenant }) => {
  const [leadVal, setLeadVal] = useState(150);
  const [closingRate, setClosingRate] = useState(20);

  const leadsCaptured = tenant.leads?.length || 10;
  const planCost = 49; // Aura Business Plan Subscription

  // Net ROI Yield calculations
  const expectedRevenue = useMemo(() => {
    const deals = Math.round(leadsCaptured * (closingRate / 100));
    return deals * leadVal;
  }, [leadsCaptured, leadVal, closingRate]);

  const roiPercentage = useMemo(() => {
    if (planCost === 0) return 0;
    return Math.round(((expectedRevenue - planCost) / planCost) * 100);
  }, [expectedRevenue, planCost]);

  return (
    <div className="bg-[#080b12] border border-white/5 p-5 rounded-3xl space-y-4 shadow-xl select-none">
      <div className="flex items-center justify-between">
        <p className="text-[10px] font-bold font-mono text-slate-450 uppercase tracking-widest flex items-center gap-1.5">
          <Calculator className="h-3.5 w-3.5 text-blue-400" />
          <span>Interactive ROI Yield</span>
        </p>
        <span className="text-[9.5px] font-mono text-slate-500 font-bold uppercase bg-white/5 px-2 py-0.5 rounded">Modeling</span>
      </div>

      <div className="space-y-3 pt-1">
        {/* Slider 1: Lead Value */}
        <div className="space-y-1.5 font-mono text-xs">
          <div className="flex items-center justify-between">
            <span className="text-slate-400 text-[10px]">Est. Lead Value:</span>
            <span className="text-white font-bold text-[11px]">${leadVal}</span>
          </div>
          <input 
            type="range" 
            min="50" 
            max="500" 
            step="10"
            value={leadVal}
            onChange={(e) => setLeadVal(Number(e.target.value))}
            className="w-full h-1 bg-white/10 rounded-lg appearance-none cursor-pointer accent-blue-500"
          />
        </div>

        {/* Slider 2: Closing Rate */}
        <div className="space-y-1.5 font-mono text-xs">
          <div className="flex items-center justify-between">
            <span className="text-slate-400 text-[10px]">Est. Closing Rate:</span>
            <span className="text-white font-bold text-[11px]">{closingRate}%</span>
          </div>
          <input 
            type="range" 
            min="5" 
            max="100" 
            step="5"
            value={closingRate}
            onChange={(e) => setClosingRate(Number(e.target.value))}
            className="w-full h-1 bg-white/10 rounded-lg appearance-none cursor-pointer accent-purple-500"
          />
        </div>

        {/* Dynamic yield output */}
        <div className="bg-[#0d121d] border border-white/5 p-3.5 rounded-2xl space-y-2 mt-2">
          <div className="flex items-center justify-between text-xs font-mono">
            <span className="text-slate-400">Expected Return:</span>
            <strong className="text-white">${expectedRevenue.toLocaleString()}</strong>
          </div>
          <div className="flex items-center justify-between text-xs font-mono border-t border-white/5 pt-2">
            <span className="text-slate-400">Net Platform ROI:</span>
            <strong className="text-emerald-450 flex items-center gap-0.5">
              <TrendingUp className="h-3.5 w-3.5" />
              {roiPercentage.toLocaleString()}%
            </strong>
          </div>
        </div>
      </div>
    </div>
  );
};
